'use client'

import { useCallback, useEffect, useMemo, useState, type CSSProperties } from 'react'
import MapPicker from './map-picker'

type Choice = { id: string; nombre: string; precio_extra: number }
type Group = { id: string; titulo: string; requerido: boolean; minimo: number; maximo: number; choices: Choice[] }
type Product = { id: string; nombre: string; descripcion: string | null; precio: number; grupos: Group[] }
type Restaurant = { nombre: string; celular: string | null; direccion_fisica: string | null; referencia: string | null; lat: number | null; lng: number | null }
type Shipping = { costo: number | null; distancia_km: number; duracion_min: number; fuente: string; permitido: boolean; razon?: string | null }
type Data = { restaurant: Restaurant; menu: Product[]; costo_vip: number }
const money = (n: number) => `S/ ${n.toFixed(2)}`
const inputStyle: CSSProperties = { width: '100%', minWidth: 0, padding: '11px 12px', color: '#edf2e9', background: '#0a0c0a', border: '1px solid #343a34', borderRadius: 9, outline: 'none' }
const labelStyle: CSSProperties = { display: 'grid', gap: 6, color: '#9aa69a', fontSize: 11 }

export default function AutopedidosPanel({ onBack, onCreated }: { onBack: () => void; onCreated: () => void }) {
  const [data, setData] = useState<Data | null>(null), [busy, setBusy] = useState(false), [error, setError] = useState(''), [notice, setNotice] = useState('')
  const [search, setSearch] = useState(''), [quantities, setQuantities] = useState<Record<string, number>>({}), [options, setOptions] = useState<Record<string, string[]>>({})
  const [address, setAddress] = useState(''), [reference, setReference] = useState(''), [lat, setLat] = useState(''), [lng, setLng] = useState(''), [vip, setVip] = useState(false), [notes, setNotes] = useState(''), [shipping, setShipping] = useState<Shipping | null>(null), [shippingBusy, setShippingBusy] = useState(false)
  const [localAddress, setLocalAddress] = useState(''), [localReference, setLocalReference] = useState(''), [localLat, setLocalLat] = useState(''), [localLng, setLocalLng] = useState('')
  const [mapTarget, setMapTarget] = useState<'local' | 'client' | null>(null)
  const load = useCallback(async () => { setBusy(true); setError(''); try { const res = await fetch('/api/local/autopedidos', { cache: 'no-store' }); const body = await res.json(); if (!res.ok || !body.ok) throw new Error(body.error || 'No se pudo cargar el menú'); setData(body.data); setLocalAddress(body.data.restaurant.direccion_fisica || ''); setLocalReference(body.data.restaurant.referencia || ''); setLocalLat(body.data.restaurant.lat == null ? '' : String(body.data.restaurant.lat)); setLocalLng(body.data.restaurant.lng == null ? '' : String(body.data.restaurant.lng)) } catch (e) { setError(e instanceof Error ? e.message : 'Error de conexión') } finally { setBusy(false) } }, [])
  useEffect(() => { void load() }, [load])
  const filtered = useMemo(() => data?.menu.filter(p => p.nombre.toLowerCase().includes(search.toLowerCase())) ?? [], [data, search])
  const selected = useMemo(() => data?.menu.filter(p => (quantities[p.id] || 0) > 0) ?? [], [data, quantities])
  const subtotal = selected.reduce((sum, p) => sum + (p.precio + p.grupos.reduce((s,g) => s + g.choices.filter(c => (options[`${p.id}:${g.id}`] || []).includes(c.id)).reduce((a,c) => a+c.precio_extra,0),0)) * quantities[p.id], 0)
  useEffect(() => {
    setShipping(null)
    const clientLat = Number(lat), clientLng = Number(lng)
    if (!Number.isFinite(clientLat) || !Number.isFinite(clientLng) || lat.trim() === '' || lng.trim() === '' || data?.restaurant.lat == null || data?.restaurant.lng == null) return
    let ignore = false; const timer = window.setTimeout(async () => { setShippingBusy(true); try { const res = await fetch('/api/local/autopedidos/shipping', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ lat: clientLat, lng: clientLng }) }); const body = await res.json(); if (!ignore && res.ok && body.ok) setShipping(body.data); else if (!ignore && body.error) setError(body.error) } catch { if (!ignore) setError('No se pudo calcular el envío.') } finally { if (!ignore) setShippingBusy(false) } }, 450)
    return () => { ignore = true; window.clearTimeout(timer) }
  }, [lat, lng, data?.restaurant.lat, data?.restaurant.lng])
  function locate(setLatitude: (v: string) => void, setLongitude: (v: string) => void) { if (!navigator.geolocation) { setError('Este navegador no permite obtener la ubicación.'); return } navigator.geolocation.getCurrentPosition(p => { setLatitude(p.coords.latitude.toFixed(6)); setLongitude(p.coords.longitude.toFixed(6)); setError('') }, () => setError('No se pudo obtener GPS. Ingresa las coordenadas manualmente.'), { enableHighAccuracy: true, timeout: 12000 }) }
  async function closeMap() {
    const isLocal = mapTarget === 'local', chosenLat = Number(isLocal ? localLat : lat), chosenLng = Number(isLocal ? localLng : lng)
    setMapTarget(null)
    if (!Number.isFinite(chosenLat) || !Number.isFinite(chosenLng)) return
    try {
      const response = await fetch(`https://nominatim.openstreetmap.org/reverse?format=json&lat=${chosenLat}&lon=${chosenLng}&accept-language=es`)
      const result = await response.json(), suggested = result.display_name?.split(',').slice(0, 4).join(', ')
      if (suggested) { if (isLocal && !localAddress.trim()) setLocalAddress(suggested); if (!isLocal && !address.trim()) setAddress(suggested) }
    } catch { /* Address remains editable and can be typed manually. */ }
  }
  async function saveLocalLocation() { setBusy(true); setError(''); try { const res = await fetch('/api/local/autopedidos', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ direccion: localAddress, referencia: localReference || null, lat: Number(localLat), lng: Number(localLng) }) }); const body = await res.json(); if (!res.ok || !body.ok) throw new Error(body.error || 'No se guardó la ubicación'); setNotice('Ubicación del local guardada.'); await load() } catch(e) { setError(e instanceof Error ? e.message : 'Error') } finally { setBusy(false) } }
  async function submit() { setBusy(true); setError(''); setNotice(''); try { const items = selected.map(p => ({ plato_id:p.id, cantidad:quantities[p.id], opciones:p.grupos.flatMap(g => (options[`${p.id}:${g.id}`] || []).map(choice_id => ({ grupo_id:g.id, choice_id }))) })); const res = await fetch('/api/local/autopedidos', { method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({ direccion:address, referencia:reference || null, lat:Number(lat), lng:Number(lng), vip, notas:notes || null, items }) }); const body = await res.json(); if (!res.ok || !body.ok) throw new Error(body.error || 'No se pudo crear el pedido'); setNotice(`Autopedido ${body.data.codigo} registrado · ${money(body.data.total)}`); setQuantities({}); setOptions({}); setAddress(''); setReference(''); setLat(''); setLng(''); setVip(false); setNotes(''); setShipping(null); onCreated() } catch(e) { setError(e instanceof Error ? e.message : 'Error de conexión') } finally { setBusy(false) } }
  const missingOptions = selected.some(p => p.grupos.some(g => { const n=(options[`${p.id}:${g.id}`]||[]).length; return n < (g.requerido ? Math.max(1,g.minimo):g.minimo) || n>g.maximo }))
  const localReady = Boolean(data?.restaurant.lat != null && data?.restaurant.lng != null)
  const clientReady = address.trim().length>=3 && Number.isFinite(Number(lat)) && lat!=='' && Number.isFinite(Number(lng)) && lng!==''
  return <div>
    <div className="local-page-heading"><div><p className="local-eyebrow">PEDIDO PARA TU LOCAL</p><h1>Autopedidos</h1><p>El cliente del pedido será {data?.restaurant.nombre || 'tu local'} ({data?.restaurant.celular || 'sin teléfono registrado'}).</p></div><button className="local-refresh" onClick={onBack}>← <span>Volver a pedidos</span></button></div>
    {notice && <div className="local-notice" role="status">✓ {notice}</div>}{error && <div className="local-error" role="alert"><span>{error}</span><button onClick={()=>setError('')}>Cerrar</button></div>}
    {busy && !data ? <div className="local-empty">Cargando menú…</div> : data && <div className="auto-layout">
      <div className="auto-main">
        <section className="auto-panel"><div className="auto-panel-heading"><div><h2>Productos de {data.restaurant.nombre}</h2><p>Busca y agrega productos. Completa las opciones obligatorias.</p></div><strong>{data.menu.length} disponibles</strong></div><input style={inputStyle} placeholder="Buscar producto…" value={search} onChange={e=>setSearch(e.target.value)}/>
          <div className="auto-product-list">{filtered.map(p => <article className="auto-product" key={p.id}><div className="auto-product-head"><div><strong>{p.nombre}</strong>{p.descripcion && <small>{p.descripcion}</small>}<span>{money(p.precio)}</span></div><div className="auto-qty"><button aria-label={`Quitar ${p.nombre}`} onClick={()=>setQuantities(q=>({...q,[p.id]:Math.max(0,(q[p.id]||0)-1)}))}>−</button><b>{quantities[p.id]||0}</b><button aria-label={`Agregar ${p.nombre}`} onClick={()=>setQuantities(q=>({...q,[p.id]:Math.min(99,(q[p.id]||0)+1)}))}>+</button></div></div>
            {(quantities[p.id]||0)>0 && p.grupos.map(g => <fieldset className="auto-options" key={g.id}><legend>{g.titulo}{g.requerido && <em> · obligatorio</em>}<small> {g.maximo>1?`elige hasta ${g.maximo}`:'elige una opción'}</small></legend><div>{g.choices.map(c=>{const key=`${p.id}:${g.id}`, checked=(options[key]||[]).includes(c.id);return <label key={c.id}><input type={g.maximo===1?'radio':'checkbox'} name={key} checked={checked} onChange={()=>setOptions(o=>{const old=o[key]||[]; const next=g.maximo===1?(checked?[]:[c.id]):checked?old.filter(x=>x!==c.id):old.length<g.maximo?[...old,c.id]:old;return {...o,[key]:next}})}/>{c.nombre}{c.precio_extra?` (+${money(c.precio_extra)})`:''}</label>})}</div></fieldset>)}
          </article>)}{filtered.length===0 && <div className="auto-empty">No hay productos que coincidan.</div>}</div>
        </section>
        <section className="auto-panel"><div className="auto-panel-heading"><div><h2>Ubicaciones para el envío</h2><p>Primero la ubicación guardada del local; luego la dirección que indica el cliente.</p></div></div>
          <div className="auto-location-card"><h3>📍 Local · {data.restaurant.nombre}</h3><p>{localReady ? `${Number(data.restaurant.lat).toFixed(6)}, ${Number(data.restaurant.lng).toFixed(6)}` : 'Falta elegir la ubicación del local para calcular el envío.'}</p><div className="auto-fields"><label style={labelStyle}>Dirección del local<input style={inputStyle} value={localAddress} onChange={e=>setLocalAddress(e.target.value)} placeholder="Dirección del restaurante"/></label><label style={labelStyle}>Referencia<input style={inputStyle} value={localReference} onChange={e=>setLocalReference(e.target.value)} placeholder="Referencia (opcional)"/></label></div><div className="auto-actions"><button className="local-refresh" onClick={()=>setMapTarget('local')}>Elegir punto en mapa</button><button className="local-refresh" onClick={()=>locate(setLocalLat,setLocalLng)}>Usar GPS del local</button><button className="local-primary-button" disabled={busy} onClick={()=>void saveLocalLocation()}>{busy?'Guardando…':'Guardar ubicación del local'}</button></div></div>
          <div className="auto-location-card"><h3>🏠 Entrega · dirección del cliente</h3><div className="auto-fields"><label style={labelStyle}>Dirección<input style={inputStyle} value={address} onChange={e=>setAddress(e.target.value)} placeholder="Calle, número, distrito"/></label><label style={labelStyle}>Referencia<input style={inputStyle} value={reference} onChange={e=>setReference(e.target.value)} placeholder="Piso, referencia (opcional)"/></label></div><div className="auto-actions"><button className="local-refresh" onClick={()=>setMapTarget('client')}>Elegir punto en mapa</button><button className="local-refresh" onClick={()=>locate(setLat,setLng)}>Usar ubicación actual</button>{lat&&lng&&<span className="auto-coordinate">Punto: {Number(lat).toFixed(6)}, {Number(lng).toFixed(6)}</span>}</div>{shippingBusy?<p className="auto-shipping">Calculando ruta y envío…</p>:shipping?.permitido?<p className="auto-shipping">Envío {money(shipping.costo!)} · {shipping.distancia_km.toFixed(2)} km · ruta por calles</p>:shipping?<p className="auto-shipping">{shipping.razon==='SUPERA_DISTANCIA_MAXIMA'?`El cliente está a ${shipping.distancia_km.toFixed(1)} km. El máximo es 15 km.`:'No se pudo calcular una ruta real por calles. Intenta de nuevo más tarde.'}</p>:lat&&lng?<p className="auto-shipping">Calculando costo de envío…</p>:<p className="auto-location-help">Elige en el mapa el punto de entrega para calcular el precio.</p>}</div>
        </section>
      </div>
      <aside className="auto-summary"><h2>Resumen del pedido</h2><p className="auto-summary-local">{data.restaurant.nombre} · {data.restaurant.celular || 'sin teléfono'}</p><div className="auto-summary-items">{selected.length?selected.map(p=><div key={p.id}><span>{quantities[p.id]} × {p.nombre}</span><strong>{money((p.precio+p.grupos.reduce((s,g)=>s+g.choices.filter(c=>(options[`${p.id}:${g.id}`]||[]).includes(c.id)).reduce((a,c)=>a+c.precio_extra,0),0))*quantities[p.id])}</strong></div>):<small>Agrega productos del menú.</small>}</div>
        <label className="auto-vip"><input type="checkbox" checked={vip} onChange={e=>setVip(e.target.checked)}/><span><b>Pedido VIP</b><small>Prioridad especial · {money(data.costo_vip)}</small></span></label><label className="auto-notes">Nota para el pedido<textarea value={notes} onChange={e=>setNotes(e.target.value)} maxLength={500} placeholder="Indicaciones adicionales (opcional)"/></label><div className="auto-total"><span>Productos</span><strong>{money(subtotal)}</strong></div><div className="auto-total"><span>Envío</span><strong>{shipping?.costo != null?money(shipping.costo):'No disponible'}</strong></div>{vip&&<div className="auto-total"><span>VIP</span><strong>{money(data.costo_vip)}</strong></div>}<div className="auto-total grand"><span>Total</span><strong>{money(subtotal+(shipping?.costo||0)+(vip?data.costo_vip:0))}</strong></div><button className="local-primary-button auto-submit" disabled={busy||!selected.length||missingOptions||!localReady||!clientReady||!shipping?.permitido} onClick={()=>void submit()}>{busy?'Registrando…':'Crear autopedido'}</button>{missingOptions&&<small className="auto-hint">Completa las opciones obligatorias de los productos.</small>}{!shipping?.permitido&&clientReady&&shipping&&!shippingBusy&&<small className="auto-hint">Se necesita una ruta real de hasta 15 km.</small>}{!localReady&&<small className="auto-hint">Guarda las coordenadas del local para activar el cálculo de envío.</small>}</aside>
    </div>}
    {mapTarget && <MapPicker title={mapTarget === 'local' ? 'Ubica el local' : 'Ubica la dirección de entrega'} lat={Number(mapTarget === 'local' ? localLat : lat) || Number(data?.restaurant.lat) || -8.3791} lng={Number(mapTarget === 'local' ? localLng : lng) || Number(data?.restaurant.lng) || -74.5539} onClose={()=>void closeMap()} onSelect={(newLat,newLng)=>{ if(mapTarget==='local'){setLocalLat(newLat.toFixed(6));setLocalLng(newLng.toFixed(6))}else{setLat(newLat.toFixed(6));setLng(newLng.toFixed(6))} }}/>}
  </div>
}
